### ISSUE TITLE
Support of `args`

### ISSUE THREAD

**Issue by shiba24** [brunorigal/autograd-minimize#1]
Hi, I love the idea of this repository - thank you for sharing it.

How about supporting extra args to the func? `args=()` part of the scipy minimize function.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html

If you navigate me I can also work on it.

**Comment by brunorigal** [comment]
This is easily done outside of the library with a lambda function. For example:
```
res = minimize(lambda x: fun(x, *args), x0)
```
Adding such an argument within the library may collide with the possibility to use functions accepting lists or dicts as variables to be optimized.

**Comment by shiba24** [comment]
That makes sense - thank you!
