### ISSUE TITLE
Possibility to install only one backend

### ISSUE THREAD

**Issue by ogencoglu** [brunorigal/autograd-minimize#9]
Having tensorflow, pytorch, jax all together in requirements creates a massive install. Would it be possible to separate the pip installation to something like `autograd-minimize[jax]`. Typically people use only one backend.

Another thing is the CPU vs GPU versions of those libraries.

**Comment by brunorigal** [comment]
Actually, if you install `pip install autograd-minimize`, only scipy is listed as a dependency in the setup.py. Then you can add jax, torch or tensorflow in cpu or gpu versions.

**Comment by ogencoglu** [comment]
Understood, thanks!
